# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'softimply/basichealthservice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: | 
      '$(Build.BuildNumber)'
      latest
