# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
- name: system.debug
  value: true

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $path = "./appsettings.json"
      $content = Get-Content -Path $path | ConvertFrom-Json
      $content.ElasticConfiguration.URI = "$(ElasticUri)"
      $content | ConvertTo-Json -Depth 5 | Set-Content -path $path

- task: PowerShell@2
  condition: eq(variables['system.debug'], 'true')
  inputs:
    targetType: inline
    script: |
      $path = "./appsettings.json"
      $content = Get-Content -Path $path -raw
      Write-Verbose -Verbose "Contents of appsettings:"
      Write-Verbose -Verbose $content
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'softimply/basichealthservice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: | 
      $(Build.BuildNumber)
      latest
